export const serviceCatalog = [
  { slug:"solar-panels", name:"Solar Panels", icon:"✦", description:"High-efficiency panels engineered for dependable clean power.", longDescription:"We specify high-performance modules for your roof, usage profile and local conditions.", benefits:["Tier-one quality modules","Optimised roof layout","Performance monitoring"] },
  { slug:"on-grid", name:"On-Grid Solar System", icon:"⌁", description:"Reduce grid dependence while exporting surplus energy.", longDescription:"A connected system that offsets daytime consumption and enables net metering where available.", benefits:["Lower monthly bills","Net-metering guidance","Fast return on investment"] },
  { slug:"off-grid", name:"Off-Grid Solar System", icon:"◒", description:"Resilient solar power for remote locations and backup needs.", longDescription:"Independent solar and storage for sites where reliability matters more than grid access.", benefits:["Battery-backed independence","Designed for remote sites","Energy resilience"] },
  { slug:"hybrid", name:"Hybrid Solar System", icon:"◈", description:"Solar, battery and grid intelligence in one flexible system.", longDescription:"A flexible architecture that prioritises solar, stores energy and keeps essential loads running.", benefits:["Smart battery dispatch","Backup for essentials","Future-ready design"] },
  { slug:"water-pumps", name:"Solar Water Pumps", icon:"◒", description:"Efficient water pumping without rising diesel or grid costs.", longDescription:"Reliable pumping systems matched to bore depth, irrigation demand and available sunlight.", benefits:["Lower irrigation costs","Robust pump selection","Agricultural expertise"] },
  { slug:"solar-lights", name:"Solar Lights", icon:"☼", description:"Bright, low-maintenance lighting for streets, campuses and homes.", longDescription:"Autonomous lighting that delivers dependable illumination with minimal infrastructure.", benefits:["Automatic dusk-to-dawn","Low maintenance","Public-space ready"] },
  { slug:"solar-cctv", name:"Solar CCTV", icon:"◉", description:"Always-on security monitoring for locations without reliable power.", longDescription:"Solar-powered surveillance designed for remote perimeters, farms and construction sites.", benefits:["24/7 monitoring","Remote deployment","Expandable systems"] },
  { slug:"solar-inverter", name:"Solar Inverter", icon:"↯", description:"Smart conversion and monitoring for stable solar performance.", longDescription:"Efficient, monitored conversion that turns every ray into useful, reliable power.", benefits:["High conversion efficiency","Real-time visibility","Compatible upgrades"] },
  { slug:"installation", name:"Solar Installation", icon:"⌂", description:"End-to-end design, installation and commissioning by experts.", longDescription:"A managed installation journey from engineering and approvals through commissioning.", benefits:["Survey to handover","Safety-first installation","Documentation included"] },
  { slug:"maintenance", name:"Maintenance & Support", icon:"✚", description:"Proactive care that keeps your system producing at its best.", longDescription:"Service plans and responsive support to protect performance throughout the system lifecycle.", benefits:["Preventive service","Fast diagnostics","Long-term care"] },
];
export const faqs = [
  { q:"How much can a solar system save me?", a:"Savings depend on your bill, roof, tariff and sunlight. Use our calculator for an indicative estimate, then request a site survey for a proposal." },
  { q:"Do you help with installation and approvals?", a:"Yes. Our team manages design, installation, commissioning and guidance for applicable local approvals and net metering." },
  { q:"How long does installation take?", a:"Most residential installations are completed within a few days after approvals and equipment are ready." },
  { q:"What maintenance does solar need?", a:"Regular visual checks and periodic cleaning keep panels productive. Our support plans also cover diagnostics and preventive service." },
  { q:"Can I add batteries later?", a:"Often, yes. We can design an on-grid system with a future-ready inverter or recommend a hybrid architecture from the start." },
];
